# Generated by Django 2.2 on 2019-10-19 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end',
            new_name='end_date_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start',
            new_name='start_date_time',
        ),
    ]
